; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;set your env you want to build. Comment line to build all environments.
;list separated by , to build selected envs.
default_envs = HCP_Tynet

[env]
platform = espressif32@6.9.0
board = nodemcu-32s
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 9600
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+
lib_compat_mode = strict
lib_deps =
	marvinroger/AsyncMqttClient@^0.8.0
	esp32async/ESPAsyncWebServer
	esp32async/AsyncTCP
	bblanchon/ArduinoJson
	plerup/EspSoftwareSerial
	ayushsharma82/ElegantOTA
	paulstoffregen/OneWire
	emelianov/modbus-esp8266
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BME280 Library
	adafruit/Adafruit AHTX0
	milesburton/DallasTemperature
   adafruit/DHT sensor library@^1.4.4
    h2zero/NimBLE-Arduino@^1.4.0
extra_scripts = pre:./WebUI/webpage/compress.py, pre:build_output.py
build_flags=-DELEGANTOTA_USE_ASYNC_WEBSERVER=1 -std=gnu++17 -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags=-std=gnu++11
;build_flags =
;	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;	-D DEBUG

[env:HCP_Tynet]
board = esp32-s3-devkitc-1
build_flags = ${env.build_flags} -D HCP_Tynet -D BUILD_ENV=\"HCP_Tynet\"

[env:esp32]
build_flags = ${env.build_flags} -D BUILD_ENV=\"esp32\"

[env:m5stack-stamps3]
board = m5stack-stamps3
build_flags = ${env.build_flags} -D M5STACK -D BUILD_ENV=\"m5stack-stamps3\"

[env:HCP_Giffordv1]
build_flags = ${env.build_flags} -D BUILD_ENV=\"HCP_Giffordv1\"

[env:HCP_Giffordv2]
board = esp32-s3-devkitc-1
platform = espressif32 @ 6.9.0
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.extra_flags =
  -DBOARD_HAS_PSRAM
extra_scripts = pre:./WebUI/webpage/compress.py, pre:build_output.py
build_flags = ${env.build_flags} -D HCP_Giffordv2 -D BUILD_ENV=\"HCP_Giffordv2\"

[env:HCP_Giffordv3]
board = esp32dev
build_flags = ${env.build_flags} -D HCP_Giffordv3 -D BUILD_ENV=\"HCP_Giffordv3\"

